name: Validate Plugin Readme

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  validate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Validate Plugin Readme
        run: wp plugin verify-readme readme.txt || exit 1
