name: Validate Plugin Readme

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  validate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if readme.txt Exists
        run: |
          if [ ! -f readme.txt ]; then
            echo "Error: readme.txt file is missing!"
            exit 1
          fi

      - name: Validate Readme Format
        run: |
          if ! grep -q "=== " readme.txt; then
            echo "Error: readme.txt is missing the main header (=== Plugin Name ===)."
            exit 1
          fi
          if ! grep -q "== Description ==" readme.txt; then
            echo "Error: readme.txt is missing the Description section."
            exit 1
          fi
          if ! grep -q "== Changelog ==" readme.txt; then
            echo "Error: readme.txt is missing the Changelog section."
            exit 1
          fi

      - name: Confirm Readme Validation
        run: echo "✅ readme.txt passed validation!"
