name: Create Issues from TODO Comments

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TODO to Issue Action
        uses: alstr/todo-to-issue-action@v5.1.7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          todo-keyword: "@TODO:" 
          file-glob: |
            **/*.php
            !vendor/**
            !node_modules
          labels: "todo, automation"
          remove-todo: false # Set to true if you want to remove TODO comments after creating issues