name: Create Issues from TODO Comments

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TODO to Issue Action
        uses: alstr/todo-to-issue-action@v5.1.7
        with:
          PROJECTS_SECRET: ${{ secrets.GITHUB_TOKEN }}
          IDENTIFIERS: [{"name": "TODO", "labels": []}]          
          AUTO_ASSIGN: 'malayladu'
          IGNORE: 'vendor/.*,node_modules/.*'                